language: haskell
ghc:
  - "7.10"
  - "7.8"
before_install:
  - cabal install codecov-haskell
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test
after_script:
  - codecov-haskell

